language: android

android:
  components:

  - tools
  - platform-tools
  - tools

  # Build tools version.
  - build-tools-26.0.1

  # Android complile sdk version.
  - android-26

  # Additional components.
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
